StoryPPW/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story4.urls')),
    path('', include('story1.urls')),
    path('', include('story5.urls')),
    path('', include('story6.urls')),
    path('', include('story7.urls')),
    path('', include('story8.urls')),
    path('', include('story9.urls')),
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('story1', views.profil, name='story1'),
  
   
]

story4/urls.py
from django.urls import path

from . import views

app_name = 'story4'

urlpatterns = [
    path('', views.home, name='awal'),
    path('home', views.home, name='home'),
    path('login', views.login, name='login'),
   
]

story5/urls.py
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('form', views.form_matkul, name='form'),
    path('Savejadwal', views.savejadwal, name='save'),
    path('jadwal', views.jadwal, name='jadwal'),
    path('delete/<int:pk>', views.delete, name='delete'),
    path('detail/<int:pk>', views.detail, name='detail'),
    
]

story6/urls.py
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('formKegiatan', views.form_kegiatan, name='formKegiatan'),
    path('formDaftar/<int:pk>', views.form_daftar, name='formDaftar'),
    path('saveKegiatan', views.save_kegiatan, name='saveKegiatan'),
    path('saveDaftar/<int:pk>', views.save_orang, name='saveDaftar'),
    path('kegiatan', views.kegiatan, name='kegiatan'),
    
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('profil', views.profil, name='profil'),
 
    
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('book', views.book, name='book'),
    path('data', views.data, name='data'),
    
    
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('SignUp', views.sign_up, name='SignUp'), 
    path('Masuk', views.masuk, name='login'),   
    path('Keluar', views.keluar, name='logout'),   
]

story1/models.py
from django.db import models

# Create your models here.

story4/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models

# Create your models here.
class Jadwal(models.Model):
    nama_matkul = models.CharField(max_length = 50)
    dosen = models.CharField(max_length = 50)
    jumlah_sks = models.IntegerField(null = True)
    tahun_ajaran = models.CharField(max_length = 15)
    ruang_kelas = models.CharField(max_length = 20,default='none')
    deskripsi_matkul = models.CharField(max_length = 300)

story6/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    nama = models.CharField(max_length = 20)
    

class Orang(models.Model):
    nama = models.CharField(max_length = 20)
    kegiatan = models.ManyToManyField(Kegiatan)

    
    

story7/models.py
from django.db import models

# Create your models here.

story6/forms.py
from django import forms
from .models import Kegiatan, Orang

class formKegiatan(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = ['nama']

    input_attrs = {
        'type' :'text',
        'placeholder' : 'Nama Kegiatan'
    }

    nama = forms.CharField(label='', required=True, max_length = 20, widget = forms.TextInput(attrs=input_attrs))

class formDaftar(forms.ModelForm):
    class Meta:
        model = Orang
        fields = ['nama']

    input_attrs = {
        'type' :'text',
        'placeholder' : 'Nama Kamu'
    }

    nama = forms.CharField(label='', required=True, max_length = 20, widget = forms.TextInput(attrs=input_attrs))

story9/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

story1/views.py
from django.shortcuts import render

# Create your views here.
def profil(request):
    return render(request, 'story1/story1.html',  {'title':'Story 1'})

story4/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html', {'title':'Home'})

def login(request):
    return render(request, 'main/login.html', {'title':'Login'})

story5/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .form import FormMatkul
from .models import Jadwal

# Create your views here.
def form_matkul(request):
    form = FormMatkul
    response = {"form":form, "title":"Tambah Jadwal"}
    return render(request,"jadwal/matkul.html",response)

def savejadwal(request):
    form = FormMatkul(request.POST)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
    return redirect("/form")
        
def delete(request, pk):
    Jadwal.objects.get(pk = pk).delete()
    return redirect("/jadwal")

def jadwal(request):
    jadwal = Jadwal.objects.all()
    response = {"jadwal":jadwal, "title":"Jadwal Kuliah"}
    return render(request,"jadwal/jadwal.html",response)

def detail(request, pk):
    detail = Jadwal.objects.get(pk=pk)
    response = {"jadwal":detail, "title":"detail"}
    return render(request,"jadwal/detail.html",response)

story6/views.py
from django.shortcuts import render,redirect
from .forms import formKegiatan, formDaftar
from .models import Kegiatan, Orang
# Create your views here.

def form_kegiatan(request):
    form = formKegiatan
    response = {'title':'Form Kegiatan', 'form':form}
    return render(request, 'kegiatan/formKegiatan.html',response)

def save_kegiatan(request):
    form = formKegiatan(request.POST)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
    return redirect('/formKegiatan')

def form_daftar(request, pk):
    form = formDaftar
    response = {'title':'Form Daftar', 'form':form, 'pk':pk}
    return render(request, 'kegiatan/formDaftar.html',response)

def save_orang(request,pk):
    form = formDaftar(request.POST)
    if (form.is_valid() and request.method == 'POST'):
        orang = form.save()
        orang.kegiatan.add(Kegiatan.objects.get(pk=pk))
    return redirect('/kegiatan')

def kegiatan(request):
    list_orang = []
    kegiatan = Kegiatan.objects.all()
    for i in kegiatan:
        list_orang.append(i.orang_set.all())
    response = {'title':'Kegiatan', 'kegiatans' : kegiatan, 'list' : list_orang}
    return render(request, 'kegiatan/Kegiatan.html', response)

story7/views.py
from django.shortcuts import render

# Create your views here.
def profil(request):
    return render(request, "accordion.html",{"title":"Profil"})

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json
# Create your views h
def book(request):
    return render(request,"book.html", {"title":"Books"})

def data(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    data = json.loads(requests.get(url).content)

    # just return a JsonResponse
    return JsonResponse(data)

story9/views.py
from django.shortcuts import render, redirect
from .forms import SignUpForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
# Create your views here.
def sign_up(request):
    form = SignUpForm
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account was created for username '+ form.cleaned_data.get('username'))
            form = SignUpForm
    
    return render(request,"SignUp.html", {"title":"Sign Up","form":form})

def masuk(request):
    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            login(request, user)
            return redirect("/home")
        else:
            messages.info(request, 'username or password incorect')
    # A backend authenticated the credentials
    
    return render(request,"Login.html", {"title":"Login"})

def keluar(request):
    logout(request)
    
    return redirect("/home")

templates/base.html
<!DOCTYPE html>
{% load static %}


<head>
    <link rel="stylesheet" href="{% static 'css/web.css' %}" />
     <title>{{title}}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% block meta %}
    {% endblock meta %}

</head>
<body>

    <header >
        <nav class = "navbar navbar-expand-lg fixed-top  navbar-light " id="header" >
        <div class = "container">
            
            <a class="navbar-brand" href="" id = "brand"><i>Farzana</i></a>
            
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#myNav" aria-controls="myNav" aria-expanded="false" aria-label="Toggle navigation" >
                <span class="navbar-toggler-icon"></span>
            </button>  

            <div  class = "collapse navbar-collapse" id="myNav">
                <ul class = "navbar-nav" >
                    <li class="nav-item"><a class="nav-link" href= "{% url 'story4:home' %} " id="menu">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'story1:story1' %}" id="menu">Story1</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'story7:profil' %}" id="menu">Profile</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'story8:book' %}" id="menu">Book</a></li>
                    <li class="nav-item dropdown" >
                        <a id="menu" class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Schedule
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#87a96b; color:white">
                            <a class="nav-link" href="{% url 'story5:form' %}" style="color:white">Tambah Jadwal</a>
                            <a class="nav-link" href="{% url 'story5:jadwal' %}" style="color:white">Lihat Jadwal</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown" >
                        <a id="menu" class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Activity
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#87a96b; color:white">
                            <a class="nav-link" href="{% url 'story6:formKegiatan' %}" style="color:white">Tambah Kegiatan</a>
                            <a class="nav-link" href="{% url 'story6:kegiatan' %}" style="color:white">Peserta</a>
                        </div>
                    </li>
                    
                    
                </ul>
                {% if request.user.is_authenticated %}
                <div class="ml-auto">
                    <ul class = "navbar-nav" >
                        <li class="nav-item"><a class="nav-link" href= "#" id="menu"><img src="{% static 'img/user.png' %}" style = "width:1cm">Halo   <i> {{request.user}}</i></a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'story9:logout' %}" id="menu"><img src="{% static 'img/log-in.png' %}" style = "width:1cm"> Logout</a></li>
                        </ul>
                </div>
                {% else %}
                <div class="ml-auto">
                    <ul class = "navbar-nav" >
                        <li class="nav-item"><a class="nav-link" href= "{% url 'story9:SignUp' %} " id="menu"><img src="{% static 'img/user.png' %}" style = "width:1cm"> Sign Up</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'story9:login' %}" id="menu"><img src="{% static 'img/log-in.png' %}" style = "width:1cm"> Login</a></li>
                        </ul>
                </div>
                {% endif %}
            </div>
            </div>

        </div> 
        </nav>
    </header>


{% block content %}

{% endblock  %}

<footer id="footer">

<div class="container" >
<div class ="row justify-content-center"> 
    <div class = col-xs-2>
    </br>
<h3 id = "sosmed" >Find Me On:</h3>

<a href="https://www.instagram.com/farzanahadifa/?hl=en"><img src = "{% static 'img/instagram.svg'%}"  style = "width:1cm"></a>
             
<a href="https://twitter.com/FHadifa">     <img src = "{% static 'img/twitter.svg' %}" style = "width:1cm"></a>
        
<a href="https://www.linkedin.com/in/farzana-hadifa-11465719a/"><img src = " {% static 'img/linkedin.svg' %}"  style = "width:1cm"></a>
<p id = "copyright">&copy 2020 FarzanaHadifa</p>
</div>  
</div>
</div>
  </footer>
  

<script type = "text/javascript"  src = "https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</body>

    