StoryPPW/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story4.urls')),
    path('', include('story1.urls')),
    path('', include('story5.urls')),
    path('', include('story6.urls')),
    path('', include('story7.urls')),
    path('', include('story8.urls')),
    path('', include('story9.urls')),
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('story1', views.profil, name='story1'),
  
   
]

story4/urls.py
from django.urls import path

from . import views

app_name = 'story4'

urlpatterns = [
    path('', views.home, name='awal'),
    path('home', views.home, name='home'),
    path('login', views.login, name='login'),
   
]

story5/urls.py
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('form', views.form_matkul, name='form'),
    path('Savejadwal', views.savejadwal, name='save'),
    path('jadwal', views.jadwal, name='jadwal'),
    path('delete/<int:pk>', views.delete, name='delete'),
    path('detail/<int:pk>', views.detail, name='detail'),
    
]

story6/urls.py
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('formKegiatan', views.form_kegiatan, name='formKegiatan'),
    path('formDaftar/<int:pk>', views.form_daftar, name='formDaftar'),
    path('saveKegiatan', views.save_kegiatan, name='saveKegiatan'),
    path('saveDaftar/<int:pk>', views.save_orang, name='saveDaftar'),
    path('kegiatan', views.kegiatan, name='kegiatan'),
    
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('profil', views.profil, name='profil'),
 
    
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('book', views.book, name='book'),
    path('data', views.data, name='data'),
    
    
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('SignUp', views.sign_up, name='SignUp'), 
    path('Masuk', views.masuk, name='login'),   
    path('Keluar', views.keluar, name='logout'),   
]

story1/models.py
from django.db import models

# Create your models here.

story4/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models

# Create your models here.
class Jadwal(models.Model):
    nama_matkul = models.CharField(max_length = 50)
    dosen = models.CharField(max_length = 50)
    jumlah_sks = models.IntegerField(null = True)
    tahun_ajaran = models.CharField(max_length = 15)
    ruang_kelas = models.CharField(max_length = 20,default='none')
    deskripsi_matkul = models.CharField(max_length = 300)

story6/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    nama = models.CharField(max_length = 20)
    

class Orang(models.Model):
    nama = models.CharField(max_length = 20)
    kegiatan = models.ManyToManyField(Kegiatan)

    
    

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

story6/forms.py
from django import forms
from .models import Kegiatan, Orang

class formKegiatan(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = ['nama']

    input_attrs = {
        'type' :'text',
        'placeholder' : 'Nama Kegiatan'
    }

    nama = forms.CharField(label='', required=True, max_length = 20, widget = forms.TextInput(attrs=input_attrs))

class formDaftar(forms.ModelForm):
    class Meta:
        model = Orang
        fields = ['nama']

    input_attrs = {
        'type' :'text',
        'placeholder' : 'Nama Kamu'
    }

    nama = forms.CharField(label='', required=True, max_length = 20, widget = forms.TextInput(attrs=input_attrs))

story9/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

story1/views.py
from django.shortcuts import render

# Create your views here.
def profil(request):
    return render(request, 'story1/story1.html',  {'title':'Story 1'})

story4/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html', {'title':'Home'})

def login(request):
    return render(request, 'main/login.html', {'title':'Login'})

story5/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .form import FormMatkul
from .models import Jadwal

# Create your views here.
def form_matkul(request):
    form = FormMatkul
    response = {"form":form, "title":"Tambah Jadwal"}
    return render(request,"jadwal/matkul.html",response)

def savejadwal(request):
    form = FormMatkul(request.POST)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
    return redirect("/form")
        
def delete(request, pk):
    Jadwal.objects.get(pk = pk).delete()
    return redirect("/jadwal")

def jadwal(request):
    jadwal = Jadwal.objects.all()
    response = {"jadwal":jadwal, "title":"Jadwal Kuliah"}
    return render(request,"jadwal/jadwal.html",response)

def detail(request, pk):
    detail = Jadwal.objects.get(pk=pk)
    response = {"jadwal":detail, "title":"detail"}
    return render(request,"jadwal/detail.html",response)

story6/views.py
from django.shortcuts import render,redirect
from .forms import formKegiatan, formDaftar
from .models import Kegiatan, Orang
# Create your views here.

def form_kegiatan(request):
    form = formKegiatan
    response = {'title':'Form Kegiatan', 'form':form}
    return render(request, 'kegiatan/formKegiatan.html',response)

def save_kegiatan(request):
    form = formKegiatan(request.POST)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
    return redirect('/formKegiatan')

def form_daftar(request, pk):
    form = formDaftar
    response = {'title':'Form Daftar', 'form':form, 'pk':pk}
    return render(request, 'kegiatan/formDaftar.html',response)

def save_orang(request,pk):
    form = formDaftar(request.POST)
    if (form.is_valid() and request.method == 'POST'):
        orang = form.save()
        orang.kegiatan.add(Kegiatan.objects.get(pk=pk))
    return redirect('/kegiatan')

def kegiatan(request):
    list_orang = []
    kegiatan = Kegiatan.objects.all()
    for i in kegiatan:
        list_orang.append(i.orang_set.all())
    response = {'title':'Kegiatan', 'kegiatans' : kegiatan, 'list' : list_orang}
    return render(request, 'kegiatan/Kegiatan.html', response)

story7/views.py
from django.shortcuts import render

# Create your views here.
def profil(request):
    return render(request, "accordion.html",{"title":"Profil"})

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json
# Create your views h
def book(request):
    return render(request,"book.html", {"title":"Books"})

def data(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    data = json.loads(requests.get(url).content)

    # just return a JsonResponse
    return JsonResponse(data)

story9/views.py
from django.shortcuts import render, redirect
from .forms import SignUpForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
# Create your views here.
def sign_up(request):
    form = SignUpForm
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account was created for username '+ form.cleaned_data.get('username'))
            form = SignUpForm
    
    return render(request,"SignUp.html", {"title":"Sign Up","form":form})

def masuk(request):
    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            login(request, user)
            return redirect("/home")
        else:
            messages.info(request, 'username or password incorect')
    # A backend authenticated the credentials
    
    return render(request,"Login.html", {"title":"Login"})

def keluar(request):
    logout(request)
    
    return redirect("/home")

story1/templates/story1/story1.html
{% extends 'base.html' %}
{% load static %}
   <head>
       <title>{{ title }}</title>
       
   </head>
   {% block content %}
   <body id="profil">
       <h1 id="judul"><i>Welcome To My Website</i></h1>
       <img src="{% static 'img/foto.JPG' %}"  width="200" height="280" class="center1">
       <h4>Seorang Mahasiswa Tahun Kedua di Fasilkom UI. <br> Pernah Belajar Bahasa Pemrograman Python dan Java.</h4>
       <br> <br>
       <div id="biodata" >
       <h5>Nama          : Farzana Hadifa</h5>
       <h5>NPM           : 1906398534</h5>
       <h5>Angkatan      : Maung 2019</h5>
       <h5>Tempat Kuliah : Fasilkom UI</h5>
       <h5>Hobi          : Membaca</h5>
       </div>
    
       <table class="center2"  >
       <td style="padding:50px">
       <table id="T"  > 
            <tr>
                <th>Riwayat Pendidikan</th>
                <th>Tahun</th>
            </tr>
            <tr>
                <td> TK IT Al-Azhar B.Aceh</td>
                <td>2006 - 2007</td>
            </tr>
            <tr>
                <td>SDN 16 B.Aceh</td>
                <td>2007 - 2013</td>
            </tr>
            <tr>
                <td>MTsN Model B.Aceh</td>
                <td>2013 - 2016</td>
            </tr>
            <tr>
                <td>MAN Model B.Aceh</td>
                <td>2016 - 2019</td>
            </tr>
            <tr>
                <td>Universitas Indonesia</td>
                <td>2019 - Sekarang</td>
            </tr>
       </table>
       </td>

       <td style="padding:80px">
       <table id="T" > 
        <tr>
            <th>Pengalaman/Organisasi</th>
            <th>Tahun</th>
        </tr>
        <tr>
            <td>Staf Cerdas Cermat SSG UI 2020</td>
            <td>2019 - 2020</td>
        </tr>
        <tr>
            <td>Staf Mentor Betis Fasilkom 2020</td>
            <td>2019 - 2020</td>
        </tr>
        <tr>
            <td>Wakil Departemen MuC Fuki</td>
            <td>2020 - Sekarang</td>
        </tr>
        <tr>
            <td>Staf MedC Saman UI</td>
            <td>2020 - Sekarang</td>
        </tr>
        <tr>
            <td>Asisten Dosen Kalkulus 1</td>
            <td>2020 - Sekarang</td>
        </tr>
   </table>
   </td>
    </table>

   
   <h2 Style = "text-align: center;">Follow Me On:</h2>
   <table class = 'center2'>
       <td >
            <a href="https://www.instagram.com/farzanahadifa/?hl=en"><img src="{% static 'img/ig.png' %}" width="60" height="60" class="center1">
            <h3 style="color:black">@farzanahadifa</h3></a></td>
        <td style="padding:10px">
            <a href=https://twitter.com/FHadifa><img src="{% static 'img/twitter.jpg' %}" width="55" height="55" class="center1" >
            <h3 style="color:black">@FHadifa</h3></a>
        </td>
        <td style="padding:10px">
            <a href=https://www.linkedin.com/in/farzana-hadifa-11465719a><img src="{% static 'img/in.png' %}" width="55" height="55" class="center1" >
            <h3 style="color:black">Farzana Hadifa</h3></a>
        </td>
   </table>
   <br>
</div>
   </body>
   {% endblock %}

story4/templates/main/home.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
<div class = "container">
  <div class = "row justify-content-between ">
      <div class = "col-md-5 mx-3" id = "foto">
      <img src="{% static 'img/MyImage.JPG' %}"   alt="foto" class="rounded-circle " Style="width:100%;"  >
      </div>

  <div class = "col-md-5 mx-4" id = "deskripsi" >
  </br>
      <h3><b>About Me:</b></h3>
      <p>
      Hello, my name is Farzana Hadifa. I was born in Kuala Lumpur, 11 October 2001. 
      I’m a second years student in computer science, University of Indonesia. 
      I learn Java and Python programming language. In my free time, i like reading a novel or watching korean drama.
     </p>
      <h3><b>Educational Background:</b></h3>
      <ul>
          <li>TK IT Al-Azhar B.Aceh: 2006 - 2007</li>
          <li>SDN 16 B.Aceh : 2007 - 2013</li>
          <li>MTsN Model B.Aceh : 2013 - 2016</li>
          <li>MAN Model B.Aceh : 2016 - 2019</li>
          <li>Universitas Indonesia : 2019 - Sekarang</li>
      </ul>
  </div>
  
  <div class = "col-md-3 mx-4 my-2 experience"  >
  </br>
      <h3><b>Academic and Seminar</b></h3>
      <ul>
          <li>Teaching Assistant Calculus 1.</li>
          <li>Participant of the seminar Business Intelligence 101 Compfest 2019</li>
          
      </ul>
  </div>

  <div class = "col-md-3 mx-4 my-2 experience"  >
  </br>
      <h3><b>Organization</b></h3>
      <ul>
          <li>Deputy of Muslimah Center Fuki 2020</li>
          <li> Staff of MedC Saman UI 2020</li>
          
      </ul>
  </div>

  <div class = "col-md-3 mx-4 my-2 experience"  >
  </br>
      <h3><b>Commitee</b></h3>
      <ul>
          <li>Staff of Cerdas Cermat SSG UI 2020  </li>
          <li>Mentor in Betis Fasilkom 2020 </li>
          
      </ul>
  </div>
</div>
</div>

</br></br></br>
{% endblock %}

story4/templates/main/login.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
<div class = "container">
    <div class="row justify-content-center">
        <div class="col-md-5 mx-4" id="login">
    <form class="form-signin" id="form">
     <div class="text-center">
      <img class="mb-4" src="{% static 'img/user.svg' %}" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">Please Log in</h1>
      <label for="inputEmail" class="sr-only">Email address</label>
      <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
        </div>
      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit" id="login_btn">Log in</button>
      <button class="btn btn-lg btn-primary btn-block" type="submit" id="login_btn">Log in With <img src = "{% static 'img/google.svg' %}"  style = "width:0.5cm"></</button>
    </form>
</div>
    </div>
    </div>

{% endblock  %}

story5/templates/jadwal/detail.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}

     <title>{{title}}</title>

{% endblock %}

{% block content %}
<body>

<div class="container">
<div class="row justify-content-center">
<div class = "column-md-6 mx-4" Style = "margin-top: 120px" >
{% if jadwal %}
   <h2>Detail {{ jadwal.nama_matkul}}: </h2>
    <table  id="T">
       <tr>
          <th>Dosen</th>
          <th>SKS</th>
          <th>Tahun Ajaran</th>
          <th>Kelas</th>
          <th>Deskripsi Matkul</th>
       </tr>
       <tr>
         <td>{{ jadwal.dosen}}</td>
         <td>{{ jadwal.jumlah_sks}}</td>
         <td>{{ jadwal.tahun_ajaran}}</td>
         <td>{{ jadwal.ruang_kelas}}</td>
         <td>{{ jadwal.deskripsi_matkul}}</td>
      </tr>
    </table>
{% endif %}
</div>
</div>
</div>

<div class="container">
<div class="row">
<div class = "column-md-6 ml-4" Style = "margin-top: 30px; margin-bottom: 58px;" >
<a href="{% url 'story5:jadwal' %}"><img src="{% static 'img/back.svg'  %}" style = "width:2cm"></a>
</div>
</div>
</div>


</body>

{% endblock  %}

story5/templates/jadwal/jadwal.html
{% extends 'base.html' %}
{% load static %}


<head>
     <title>{{title}}</title>
</head>

{% block content %}
<body>
  <div class="container">
    <div class="row justify-content-center">
    <div class = "column-md-6 mx-4" >
<h3 Style = "margin-top: 120px">Jadwal Kuliah Semester 3:</h3>

{% if jadwal %}
<ol>
{% for matkul in jadwal %}
  <li style="font-size: 19px"> {{ matkul.nama_matkul }} 
    <a style = "color:#87a96b" href="{% url 'story5:detail' matkul.pk %}">detail</a>
    <a type="button" style = "color:#87a96b" href="{% url 'story5:delete' matkul.pk %}" onclick="return confirm('Anda yakin mau menghapus matkul {{ matkul.nama_matkul }} ?');">delete</a></li>
{% endfor %}
</ol>
{% endif %}
</div>
</div>
</div>

</br></br></br>
</body>
{% endblock  %}

story5/templates/jadwal/matkul.html
{% extends 'base.html' %}
{% load static %}


<head>
     <title>{{title}}</title>
</head>

{% block content %}
<body>
 <div class = "container">
     <div class="row justify-content-center">
          <div class="col-md-4">

<form method = "POST" action = "Savejadwal" id = "formMatkul">
<table>
{% csrf_token %}
{{ form.as_table }}
</table>
<button  type="submit" class="btn btn-secondary"  style="background-color:#87a96b;" >Tambah</button>
</form>
</br></br>
</div>
</div>
</div>
</body>


{% endblock  %}

story6/templates/kegiatan/Kegiatan.html
{% extends 'base.html' %}
{% load static %}


<head>
     <title>{{title}}</title>
     <meta charset="UTF-8">
</head>

{% block content %}
<body>
    <div style = "margin-top: 120px; margin-bottom: 120px;">
    <h2 class="text-center"  >Kegiatan dan Peserta</h2></br>

    {% if kegiatans %}
   <table class="table table-striped table-responsive-md" >
        <tr style="background-color:#b3ce9d;" >
            {% for kegiatan in kegiatans %}
            <th >{{kegiatan.nama}}</th>
            {% endfor %}
        </tr>
        <tr >
            {% for orang in list %}
            <td ><ol>
            {% for i in orang %}
            <li>{{i.nama}}</li> 
            {% endfor %}
            </ol></td>
            {% endfor %}
        </tr>
        <tr style="background-color:#b3ce9d;">
            {% for kegiatan in kegiatans %}
            <th ><a  href="{% url 'story6:formDaftar' kegiatan.pk %}"><button  type="button" class="btn btn-outline-dark" ><b>Daftar</b></button></a></th>
            {% endfor %}
        </tr>
    
   </table>

{% endif %}
</div>
</body>


{% endblock  %}

story6/templates/kegiatan/formDaftar.html
{% extends 'base.html' %}
{% load static %}


<head>
    <meta charset="UTF-8">
     <title>{{title}}</title>

</head>

{% block content %}
<body>
 <div class = "container">
     <div class="row justify-content-center">
          <div class="col-md-5 mx-4 ">
<form method = "POST" action = "{% url 'story6:saveDaftar' pk %}" id = "formMatkul">
{% csrf_token %}
{{ form.as_p }}
<button  type="submit" class="btn btn-secondary"  style="background-color:#87a96b;" >Daftar</button>
</form>

</div>
</div>
</div>
<div class = "container">
    <h5>Cancel</h5>
    <a href="{% url 'story6:kegiatan' %}"><img src="{% static 'img/back.svg'  %}" style = "width:1cm "></a>
</div>
</br></br></br>
</body>


{% endblock  %}

story6/templates/kegiatan/formKegiatan.html
{% extends 'base.html' %}
{% load static %}


<head>
     <title>{{title}}</title>
     <meta charset="UTF-8">
</head>

{% block content %}
<body>
 <div class = "container">
     <div class="row justify-content-center">
          <div class="col-md-5 mx-4 ">
<form method = "POST" action = "saveKegiatan" id = "formMatkul">
{% csrf_token %}
{{ form.as_p }}
<button  type="submit" class="btn btn-secondary"  style="background-color:#87a96b;" >Tambah</button>
</form>

</div>
</div>
</div>
</body>


{% endblock  %}

story7/templates/accordion.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}	
<script type = "text/javascript" 
    src = "https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js">
</script>
<script src="{% static 'js/accordion.js' %}"></script>
<link href="https://fonts.googleapis.com/css2?family=Castoro&family=Nerko+One&family=Roboto:wght@300;400&display=swap" rel="stylesheet"> 
<style>
    .isi{
    display: none;
    font-family: 'Castoro', serif;
     
    }

    .card{
    width: 700px;
    background-color: rgb(238, 234, 234);
    }

  

    .card-header{
    background-color: #94bb81;
    font-family: 'Nerko One', cursive;
    font-size:20px;
    }
</style>

{% endblock meta %}

<body>
{% block content %}
</br></br></br></br>

<h1 style="font-family: 'Nerko One', cursive;" class = "text-center">ABOUT ME</h1></br>

<div class="card container col-12">
    <div   class=" card-header row">
        <div class=" col-10  title">
            + Riwayat Pendidikan
        </div> 
        
            <div  class="up col-1"><button type="button" class="btn btn-outline">^</button></div> 
            <div class="down col-1"><button type="button" class="btn btn-outline">v</button></div>       
        
    </div> 
    <div class="card-body  isi mx-4">
        <ul>
            <li>TK IT Al-Azhar B.Aceh: 2006 - 2007</li>
            <li>SDN 16 B.Aceh : 2007 - 2013</li>
            <li>MTsN Model B.Aceh : 2013 - 2016</li>
            <li>MAN Model B.Aceh : 2016 - 2019</li>
            <li>Universitas Indonesia : 2019 - Sekarang</li>
        </ul>
    </div>

    <div  class=" card-header row">
    
        <div class=" col-10  title">
            + Activity
        </div> 
        
       
            <div  class="up col-1"><button type="button" class="btn btn-outline">^</button></div> 
            <div class="down col-1"><button type="button" class="btn btn-outline">v</button></div>       
       
     
    </div> 
    <div class="card-body isi mx-4">
       <p style="text-align:justify">Saat ini saya sedang menempuh pendidikan sarjana
           di jurusan ilmu komputer,Fasilkom,Universitas Indonesia.
           Di kampus saya menjadi asisten dosen kalkulus 1 dan wakil
           departemen MUC Fuki Fasilkom 2020.Saya juga aktif di paguyuban daerah dan saat ini diamanahi menjadi PJ Try Out SSG UI 2021
           dan staf MedC Saman UI 2020/2021.
        </p>
    </div>

    <div class="card-header row">
        <div class=" col-10  title">
            + Organisasi
        </div>
         
       
            <div  class="up col-1"><button type="button" class="btn btn-outline">^</button></div> 
            <div class="down col-1"><button type="button" class="btn btn-outline">v</button></div>       
     
    </div>  
    <div class=" card-body isi mx-4">
        <ul>
            
            <li> Wakil departemen Muslimah Center Fuki 2020</li>
            <li> Staff MedC Saman UI 2020</li>
            
        </ul>
    </div>
    
    <div class="card-header row">
        <div class="col-10 title">
             + Kepanitiaan 
        </div> 
       
            <div  class="up col-1"><button type="button" class="btn btn-outline">^</button></div> 
            <div class="down col-1"><button type="button" class="btn btn-outline">v</button></div>       
       
    </div>  
    <div class="isi mx-4">
        <ul>
            <li> PJ Divisi Try Out SSG UI 2021</li>
            <li>Staff Cerdas Cermat SSG UI 2020  </li>
            <li>Mentor Betis Fasilkom 2020 </li>
        </ul>
    </div>

    <div class="card-header row">  
        <div class="col-10  title">
            + Prestasi
        </div> 
     
            <div  class="up col-1"><button type="button" class="btn btn-outline">^</button></div> 
            <div class="down col-1"><button type="button" class="btn btn-outline">v</button></div>       
    </div>  
    <div class="card-body  isi mx-4">
        <ul>
            <li>Finalis OSA 2019</li>
            <li>Juara 2 Cerdas Cermat Pascal 2019 </li>
        </ul>
    </div>


</div>
</br></br>
 {% endblock %} 
 </body> 

story8/templates/book.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}	
<script type = "text/javascript" 
    src = "https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js">
</script>
<script src="{% static 'js/book.js' %}"></script>
<link href="https://fonts.googleapis.com/css2?family=Castoro&family=Nerko+One&family=Roboto:wght@300;400&display=swap" rel="stylesheet"> 
<link rel="stylesheet" href="{% static 'css/style.css' %}" />

{% endblock meta %}
{% block content %}
</br></br></br></br>
<div class="container">
<input class="col-5" type="text" id="keyword" placeholder="cari buku...">
<br><br><table  id="buku" class="table ">
</table>
</div>

{% endblock %}

story9/templates/Login.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
<div class = "container">
</br></br></br><br><br>
    <div class="row justify-content-center">
        <div class="col-md-4 mx-4" >
          <h1 class="text-center">Login</h1><br>
          <form method="POST" action="Masuk">
            {% csrf_token %}
            <label >Username:</label>
            <input type="text"  name="username"><br>
            <label >Password :</label>
            <input type="password"  name="password"><br>
            <br>
            <button  type="submit" class="btn btn-secondary "  style="background-color:#87a96b;" >Login</button>
          </form>

          {% for message in messages %}
          <b>{{message}}</b>
          {% endfor %}
          <br>
          <h5>Doesn't have an account? <a href="{% url 'story9:SignUp' %}">Sign Up</a></h5>
</div>
    </div>
    </div>
<br><br><br>
{% endblock  %}

story9/templates/SignUp.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
<div class = "container">
</br></br></br><br><br>
    <div class="row justify-content-center">
        <div class="col-md-5 mx-4" >
    <h1 class="text-center">Sign Up</h1><br>
    <form method="POST">
     {% csrf_token %}
     <table>
      <tr><td>{{form.username.label}}</td><td>: {{form.username}}</td></tr>

      <tr><td>{{form.password1.label}}</td><td>: {{form.password1}}</td></tr>
      <tr><td>{{form.password2.label}}</td><td>: {{form.password2}}</td></tr>
      </table>
     <br>
     <button  type="submit" class="btn btn-secondary "  style="background-color:#87a96b;" >Register Account</button>
    </form>
    <b>{{form.errors}}</b>
{% for message in messages %}
<b>{{message}}</b>
{% endfor %}
<br>
<h5>Already have an account? <a href="{% url 'story9:login' %}">Login</a></h5>
</div>

    </div>
    </div>
    <br><br><br>
{% endblock  %}